version: "3.7"

services:
  app:
    build: .
    container_name: dataholics
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
  db:
    container_name: "database"
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dataholics
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=vini
      - MYSQL_PASSWORD=root
